service:
  name: feedApp
environment: local

server:
  port: 8081

spring:
  data:
    mongodb:
      uri: mongodb+srv://ravibala-13:bals1999@cluster0.hfo0i.mongodb.net/?retryWrites=true&w=majority
      database: feedAppJava

